### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by yorik100** [xaw3ep/NoCheatPlus#14]
### Full output of /ncp version
![image](https://user-images.githubusercontent.com/16320315/63980108-f1be0200-caba-11e9-9bdc-e35d37e86b4e.png)
### Describe the issue
![image](https://user-images.githubusercontent.com/16320315/63980063-d652f700-caba-11e9-863b-17bb39805523.png)
### How to reproduce the issue
Start the server with latest NCP build
### Extra links/Videos (Including debug logs)
![image](https://user-images.githubusercontent.com/16320315/63980083-dfdc5f00-caba-11e9-84c4-718d2e44e6d4.png)
### Any possible config options changed or plugins that may cause interference?
Nope

**Comment by xaw3ep** [comment]
Where did you get that version?

**Comment by yorik100** [comment]
> 
> 
> Where did you get that version?

https://ci.codemc.org/job/xaw3ep/job/NoCheatPlus-1.14-Xaw3ep/
Last build (#14), 7 days 12 hr ago

**Comment by MarkElf** [comment]
CodeMC's compile command wasn't updated after the compat branch was merged with the main branch it seems. That version would at best only support 1.13-1.14.4 without (obvious) issues.

**Comment by xaw3ep** [comment]
Not fully support 1.12 below but you can try this release:
https://github.com/xaw3ep/NoCheatPlus/releases/tag/v1.4
