### ISSUE TITLE
Combined.Enderpearl: 'default' activation flag is bugged

### ISSUE THREAD

**Issue by Lysandr0** [xaw3ep/NoCheatPlus#17]
(Posting in this tracker instead of @CaptainObvious0's since I'm seeing this fork getting fixed/updated the most out of the two, currently)
### Full output of /ncp version
```
[INFO] ---- Version information ----
[INFO] #### Server ####
[INFO] git-Spigot-94af569-5d335e9 ~MC: 1.14.4~
[INFO] detected: 1.14.4
[INFO] #### NoCheatPlus ####
[INFO] Plugin: 3.16.1-SNAPSHOT-b1153-CustomFork
[INFO] MCAccess: 1.13-1.14.4|? / Bukkit-API
[INFO] Features:
[INFO] blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | MCAccessBukkitModern
[INFO] checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[INFO] defaults: pvpKnockBackVelocity
[INFO] packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | NoSlow
[INFO] Hooks: AllViolations~NCP~ 1.0
[INFO] #### Related Plugins ####
[INFO] ProtocolLib v4.5.0-SNAPSHOT
```
### Describe the issue
As the title says.
### How to reproduce the issue
Take an enderpearl and throw against a wall/obstacle, you should be able to successfully throw it, even with `checks.combined.enderpearl.preventclickblock` set to true

### Any possible config options changed or plugins that may cause interference?
Default config

**Comment by xaw3ep** [comment]
Try setting checks.combined.enderpearl.active to true to see any difference?

**Comment by Lysandr0** [comment]
Setting the flag to `true` instead of `default` fixed the issue :)
Might want to have a look at the `default` activation flag, or just set every `default` flag to `true` in the config.

**Comment by MarkElf** [comment]
The 'default' flag is intended to be used when a check is either enabled or disabled depending on a server's version. I'm not entirely sure how that's handled, or which class that would be in exactly. but I do agree that setting most checks to 'true' rather than 'default' is an easy way to fix some checks sometimes not enabling (correctly) when at 'default'.

**Comment by xaw3ep** [comment]
The 'default' will be returned true if it is checked by pData.isCheckActive but this one was config.getBoolean() so the 'default' one will always return false

**Comment by xaw3ep** [comment]
Just a mistake from commit:
https://github.com/NoCheatPlus/NoCheatPlus/commit/cf8f4826c530872d86e2f66da486cd28c0c7f365
Nothing serious to worry about.
