### ISSUE TITLE
Missing Entries: Almost all blocks in the game

### ISSUE THREAD

**Issue by B-Knight49** [xaw3ep/NoCheatPlus#57]
### Full output of /ncp version

> [14:43:31 INFO]: ---- Version information ----
> [14:43:31 INFO]: #### Server ####
> [14:43:31 INFO]: git-Paper-298 ~MC: 1.15.2~
> [14:43:31 INFO]: detected: 1.15.2
> [14:43:31 INFO]: #### NoCheatPlus ####
> [14:43:31 INFO]: Plugin: 3.17-SNAPSHOT-b5.9.1
> [14:43:31 INFO]: MCAccess: 1.13-1.16.1|? / Bukkit-API
> [14:43:31 INFO]: Features:
> [14:43:31 INFO]: blocks:
> [14:43:31 INFO]: checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
> [14:43:31 INFO]: defaults: pvpKnockBackVelocity
> [14:43:31 INFO]: packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
> [14:43:31 INFO]: Hooks: Citizens2~cncp~ 2.0 | InfiniteJump 1.2.9 | mcMMO~cncp~ 2.3 | ViolationFrequency~NCP~ 1.0
> [14:43:31 INFO]: #### Related Plugins ####
> [14:43:31 INFO]: CompatNoCheatPlus v6.6.5-RC-sMD5NET-b90 | ProtocolLib v4.6.0 | ProtocolSupport v4.29-dev | ConditionalCommands v1.5

### Describe the issue
See the log attached below.
Seems like basically every block in the game is missing entries of some kind.

### How to reproduce the issue
- Download NCP 5.9.1
- Start server
- Check console

### Extra links/Videos (Including debug logs)
https://gist.github.com/B-Knight49/f3a6ffcad4fa1de708c3ee991cdfc11f

### Any possible config options changed or plugins that may cause interference?
Unaware of any.

Let me know if I'm being stupid. I'm particularly tired and not with it today.

**Comment by MarkElf** [comment]
Outdated version.
